// flow-typed signature: 42c3c7089a213c6b198e8dc2ee71df25
// flow-typed version: <<STUB>>/react-slider_v^0.11.2/flow_v0.78.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-slider/react-slider' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-slider/react-slider.js' {
  declare module.exports: $Exports<'react-slider/react-slider'>;
}
